In [1]:
import matplotlib.pyplot as plt
from matplotlib import rcParams
import matplotlib.image as mpimg
from matplotlib.offsetbox import OffsetImage, AnnotationBbox

import seaborn as sns
sns.set_theme(style="whitegrid")

import pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

import os
from unidecode import unidecode
import geojson

import matplotlib.font_manager as font_manager

POPPINS_LIGHT_PATH = "./fonts/Poppins-Light.ttf"
POPPINS_REGULAR_PATH = "./fonts/Poppins-Regular.ttf"
POPPINS_SEMIBOLD_PATH = "./fonts/Poppins-SemiBold.ttf"

font_manager.fontManager.addfont(POPPINS_LIGHT_PATH)
font_manager.fontManager.addfont(POPPINS_REGULAR_PATH)
font_manager.fontManager.addfont(POPPINS_SEMIBOLD_PATH)

poppins_light = font_manager.FontProperties(fname=POPPINS_LIGHT_PATH)
poppins_regular = font_manager.FontProperties(fname=POPPINS_REGULAR_PATH)
poppins_semibold = font_manager.FontProperties(fname=POPPINS_SEMIBOLD_PATH)

plt.rcParams["font.family"] = poppins_light.get_name()

In [2]:
df_sig = pd.read_excel('./ignore/tables/africa_cities.xlsx')
df_jal = pd.read_excel('./ignore/tables/Modes_of_Transport_per_City-pourAlbane.xlsx')
df_jal = df_jal.ffill() # cellules fusionnées

In [3]:
df_jal.head(5)

,Pays,Ville,Nombre d'habitants en 2020 - Africapolis (agglomération),Nombre d'habitants en 2025 Africapolis (agglomération),Nombre d'habitants en 2030 - Africapolis (agglomération),Nombre d'habitants en 2024 (ville),Mode de transport,Mode de transport - détails,Situation au 01/01/25,KM d'infrastructure
0,Rwanda,Kigali,3000382.0,3617618,5192442,1287950.0,BRT,phase 1,Planned,38.0
1,Rwanda,Kigali,3000382.0,3617618,5192442,1287950.0,BRT,phase 2,Planned,38.0
2,Kenya,Nairobi,7573673.0,15954823,17960645,5541170.0,BRT,ligne 1,Under construction,27.0
3,Kenya,Nairobi,7573673.0,15954823,17960645,5541170.0,BRT,ligne 2,Under construction,27.0
4,Kenya,Nairobi,7573673.0,15954823,17960645,5541170.0,BRT,ligne 3,Under construction,20.0

In [4]:
def format_number(n):
    if n >= 1_000_000:
        return f"{round(n / 1_000_000, 1)}M" 
    elif n >= 10_000:
        return f"{round(n / 1_000)}k"
    return str(n)

<img src="./d0-3_2301-fig-ade-legende_en.png" alt="legend" style="width:500px;"/>

In [5]:
palette = {
    ("BHNS", "Planned") : "#938fc1",
    ("BHNS", "Under construction") : "#6d69a9",
    ("BHNS", "Operational") : "#494794",

    ("BRT", "Planned") : "#ba96c4",
    ("BRT", "Under construction") : "#a16aa9",
    ("BRT", "Operational") : "#8b4292",

    ("Suburban rail", "Planned") : "#cfe09c",
    ("Suburban rail", "Under construction") : "#b8d26d",
    ("Suburban rail", "Operational") : "#a4c73f",

    ("Tramway", "Planned") : "#91b4de",
    ("Tramway", "Under construction") : "#6199d2",
    ("Tramway", "Operational") : "#1984c6",

    ("Metro", "Planned") : "#a2d5d0",
    ("Metro", "Under construction") : "#73c4bd",
    ("Metro", "Operational") : "#2eb4a8",

    ("Cable", "Planned") : "#748fb1",
    ("Cable", "Under construction") : "#436b91",
    ("Cable", "Operational") : "#194f76",
    
} # else : #949599

mode_icons = {
    'BHNS' : './icons/bhns.png',
    'BRT' : './icons/brt.png',
    'Suburban rail' : './icons/suburban_rail.png',
    'Tramway' : './icons/tramway.png',
    'Metro' : './icons/metro.png',
    'Cable' : './icons/cable.png',

}

situation_order = [
    "Planned",
    "Under construction",
    "Operational"
]

transport_order = [
    "BHNS",
    "BRT",
    "Cable",
    "Tramway",
    "Metro",
    "Suburban rail"
]

In [6]:
df_sig

,fid,OBJECTID,Join_Count,CITY_NAME,GMI_ADMIN,ADMIN_NAME,FIPS_CNTRY,CNTRY_NAME,STATUS,POP,POP_RANK,POP_CLASS,PORT_ID,LABEL_FLAG,CONTINENT,SQMI,SQKM,Name,x,y
0,1,1.0,1.0,Jamestown,SHN,St. Helena,SH,St. Helena,National and provincial capital,637,7,"Less than 50,000",46690.0,0.0,Africa,1.158346e+07,3.000115e+07,Jamestown,-5.705001,-15.921999
1,2,2.0,1.0,Praia,CPV,Cape Verde,CV,Cape Verde,National capital,113364,5,"100,000 to 249,999",45910.0,0.0,Africa,1.158346e+07,3.000115e+07,Praia,-23.520996,14.922999
2,3,3.0,1.0,Santa Cruz de Tenerife,ESP-CNR,Canarias,SP,Spain,Provincial capital,222190,5,"100,000 to 249,999",38160.0,0.0,Africa,1.158346e+07,3.000115e+07,Santa Cruz de Tenerife,-16.250004,28.466703
3,4,4.0,1.0,Las Palmas,ESP-CNR,Canarias,SP,Spain,Other,378495,4,"250,000 to 499,999",38170.0,0.0,Africa,1.158346e+07,3.000115e+07,Las Palmas,-15.416703,28.150002
4,5,5.0,1.0,Funchal,PRT-MDR,Madeira,PO,Portugal,Provincial capital,100847,5,"100,000 to 249,999",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Funchal,-16.821936,32.645160
5,6,6.0,1.0,Laayoune,NaN,Saguia el Hamra,MO,Morocco,Other,-999,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Laayoune,-13.179996,27.000000
6,7,7.0,1.0,Fderik,MRT-TZM,Tiris Zemmour,MR,Mauritania,Provincial capital,-999,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Fderik,-12.707001,22.679001
7,8,8.0,1.0,Rabat,MAR-NWT,North-West,MO,Morocco,National and provincial capital,1655753,2,"1,000,000 to 4,999,999",45787.0,0.0,Africa,1.158346e+07,3.000115e+07,NaN,-6.832998,34.014996
8,9,9.0,1.0,Melilla,ESP-PS2,Melilla,SP,Spain,Provincial capital,67838,6,"50,000 to 99,999",45710.0,1.0,Africa,1.158346e+07,3.000115e+07,Melilla,-2.965959,35.316486
9,10,10.0,1.0,Fes,MAR-CNR,Centre-North,MO,Morocco,Provincial capital,964891,3,"500,000 to 999,999",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Fes,-4.995999,34.044003
10,11,11.0,1.0,Meknes,MAR-CSO,Centre-South,MO,Morocco,Provincial capital,545705,3,"500,000 to 999,999",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Meknes,-5.556996,33.903999
11,12,12.0,1.0,Ceuta,ESP-PS1,Ceuta,SP,Spain,Provincial capital,75861,6,"50,000 to 99,999",45730.0,1.0,Africa,1.158346e+07,3.000115e+07,Ceuta,-5.316696,35.883297
12,13,13.0,1.0,Oran,DZA-ORA,Oran,AG,Algeria,Other,645984,3,"500,000 to 999,999",45640.0,1.0,Africa,1.158346e+07,3.000115e+07,NaN,-0.520002,35.749998
13,14,14.0,1.0,Sidi-Bel-Abbes,DZA-SBA,Sidi bel Abbes,AG,Algeria,Provincial capital,191769,5,"100,000 to 249,999",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Sidi-Bel-Abbes,-0.639000,35.197002
14,15,15.0,1.0,Tlemcen,DZA-TLM,Tlemcen,AG,Algeria,Provincial capital,132341,5,"100,000 to 249,999",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Tlemcen,-1.314000,34.883001
15,16,16.0,1.0,Oujda,MAR-EST,Eastern,MO,Morocco,Provincial capital,405253,4,"250,000 to 499,999",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Oujda,-1.911996,34.688997
16,17,17.0,1.0,Casablanca,MAR-CEN,Centre,MO,Morocco,Provincial capital,3144909,2,"1,000,000 to 4,999,999",45793.0,0.0,Africa,1.158346e+07,3.000115e+07,NaN,-7.632000,33.605001
17,18,18.0,1.0,Marrakech,MAR-TNF,Tensift,MO,Morocco,Provincial capital,839296,3,"500,000 to 999,999",0.0,0.0,Africa,1.158346e+07,3.000115e+07,NaN,-8.011998,31.631004
18,19,19.0,1.0,Bechar,DZA-BCH,Bechar,AG,Algeria,Provincial capital,143382,5,"100,000 to 249,999",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Bechar,-2.220003,31.608000
19,20,20.0,1.0,Agadir,MAR-SOU,South,MO,Morocco,Provincial capital,698310,3,"500,000 to 999,999",45803.0,0.0,Africa,1.158346e+07,3.000115e+07,NaN,-9.611001,30.418002
20,21,21.0,1.0,Adrar,DZA-ADR,Adrar,AG,Algeria,Provincial capital,-999,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Adrar,-0.289998,27.867996
21,22,22.0,1.0,Tindouf,DZA-TND,Tindouf,AG,Algeria,Other,-999,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Tindouf,-8.160003,27.700002
22,23,23.0,1.0,Kiffa,MRT-ASB,Assaba,MR,Mauritania,Provincial capital,-999,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Kiffa,-11.403999,16.616997
23,24,24.0,1.0,Kaedi,MRT-GRG,Gorgol,MR,Mauritania,Provincial capital,-999,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Kaedi,-13.497003,16.152003
24,25,25.0,1.0,Selibabi,MRT-GDM,Guidimaka,MR,Mauritania,Provincial capital,-999,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Selibabi,-12.176001,15.161004
25,26,26.0,1.0,Kayes,MLI-KAY,Kayes,ML,Mali,Provincial capital,97464,6,"50,000 to 99,999",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Kayes,-11.429001,14.448996
26,27,27.0,1.0,Catio,GNB-TMB,Tombali,PU,Guinea-Bissau,Provincial capital,9898,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Catio,-15.166701,11.216700
27,28,28.0,1.0,Boke,GIN-BOK,Boke,GV,Guinea,Provincial capital,15460,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Boke,-14.297004,10.938996
28,29,29.0,1.0,Bo,SLE-STH,Southern,SL,Sierra Leone,Provincial capital,174354,5,"100,000 to 249,999",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Bo,-11.734002,7.967997
29,30,30.0,1.0,Robertsport,LBR-GCM,Grand Cape Mount,LI,Liberia,Provincial capital,11969,7,"Less than 50,000",45930.0,0.0,Africa,1.158346e+07,3.000115e+07,Robertsport,-11.366703,6.750000
30,31,31.0,1.0,Telimele,GIN-TLM,Telimele,GV,Guinea,Provincial capital,30311,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Telimele,-13.042998,10.905003
31,32,32.0,1.0,Fria,GIN-FRI,Fria,GV,Guinea,Provincial capital,-999,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Fria,-13.552002,10.377999
32,33,33.0,1.0,Boffa,GIN-BOF,Boffa,GV,Guinea,Provincial capital,2332,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Boffa,-14.042997,10.185003
33,34,34.0,1.0,Kindia,GIN-KIN,Kindia,GV,Guinea,Provincial capital,117062,5,"100,000 to 249,999",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Kindia,-12.866004,10.054998
34,35,35.0,1.0,Conakry,GIN-CNK,Conakry,GV,Guinea,National and provincial capital,1767200,2,"1,000,000 to 4,999,999",45855.0,1.0,Africa,1.158346e+07,3.000115e+07,Conakry,-13.671999,9.549999
35,36,36.0,1.0,Forecariah,GIN-FRC,Forecariah,GV,Guinea,Provincial capital,12358,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Forecariah,-13.097997,9.430002
36,37,37.0,1.0,Makeni,SLE-NRT,Northern,SL,Sierra Leone,Provincial capital,87679,6,"50,000 to 99,999",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Makeni,-12.043998,8.881002
37,38,38.0,1.0,Freetown,SLE-WAR,Western Area,SL,Sierra Leone,National and provincial capital,802639,3,"500,000 to 999,999",45862.0,0.0,Africa,1.158346e+07,3.000115e+07,Freetown,-13.239000,8.486001
38,39,39.0,1.0,Pita,GIN-PIT,Pita,GV,Guinea,Provincial capital,20052,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Pita,-12.401001,11.079999
39,40,40.0,1.0,Dalaba,GIN-DAL,Dalaba,GV,Guinea,Provincial capital,-999,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Dalaba,-12.272004,10.656000
40,41,41.0,1.0,Mamou,GIN-MAM,Mamou,GV,Guinea,Provincial capital,41619,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Mamou,-12.092004,10.374003
41,42,42.0,1.0,Nouadhibou,MRT-DND,Dakhlet Nouadhibou,MR,Mauritania,Other,72337,6,"50,000 to 99,999",45812.0,0.0,Africa,1.158346e+07,3.000115e+07,Nouadhibou,-17.066736,20.900052
42,43,43.0,1.0,Atar,MRT-ADR,Adrar,MR,Mauritania,Provincial capital,-999,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Atar,-13.050000,20.511000
43,44,44.0,1.0,Akjoujt,MRT-INC,Inchiri,MR,Mauritania,Provincial capital,-999,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Akjoujt,-14.391000,19.746999
44,45,45.0,1.0,Tidjikdja,MRT-TGN,Tagant,MR,Mauritania,Provincial capital,-999,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Tidjikdja,-11.430999,18.558000
45,46,46.0,1.0,Aleg,MRT-BRK,Brakna,MR,Mauritania,Provincial capital,-999,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Aleg,-13.908996,17.057997
46,47,47.0,1.0,Thies,SEN-THI,Thies,SG,Senegal,Provincial capital,252320,4,"250,000 to 499,999",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Thies,-16.923996,14.805000
47,48,48.0,1.0,Dakar,SEN-DKR,Dakar,SG,Senegal,National and provincial capital,2476400,2,"1,000,000 to 4,999,999",45820.0,1.0,Africa,1.158346e+07,3.000115e+07,NaN,-17.451999,14.687001
48,49,49.0,1.0,Nouakchott,MRT-TRR,Trarza,MR,Mauritania,National capital,661400,3,"500,000 to 999,999",0.0,0.0,Africa,1.158346e+07,3.000115e+07,NaN,-15.977997,18.083997
49,50,50.0,1.0,Louga,SEN-LOU,Louga,SG,Senegal,Provincial capital,-999,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Louga,-16.083297,15.750000
50,51,51.0,1.0,Rosso,MRT-TRR,Trarza,MR,Mauritania,Provincial capital,9923,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Rosso,-15.798996,16.512003
51,52,52.0,1.0,Saint Louis,SEN-STL,Saint-Louis,SG,Senegal,Other,-999,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Saint Louis,-16.297839,15.951213
52,53,53.0,1.0,Diourbel,SEN-DRB,Diourbel,SG,Senegal,Provincial capital,-999,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Diourbel,-16.234002,14.652999
53,54,54.0,1.0,Fatick,SEN-FTC,Fatick,SG,Senegal,Provincial capital,-999,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Fatick,-16.416000,14.344002
54,55,55.0,1.0,Kaolack,SEN-KLC,Kaolack,SG,Senegal,Provincial capital,-999,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Kaolack,-16.095996,14.142996
55,56,56.0,1.0,Kerewan,GMB-NBA,North Bank,GA,The Gambia,Provincial capital,2751,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Kerewan,-16.094997,13.493997
56,57,57.0,1.0,Banjul,GMB-BNJ,Banjul,GA,The Gambia,National capital and provincial capital enclave,34589,7,"Less than 50,000",45825.0,1.0,Africa,1.158346e+07,3.000115e+07,Banjul,-16.596792,13.463955
57,58,58.0,1.0,Bathurst,GMB-BNJ,Banjul,GA,The Gambia,Provincial capital,34589,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Bathurst,-16.588998,13.455000
58,59,59.0,1.0,Mansa Konko,GMB-LRI,Lower River,GA,The Gambia,Provincial capital,-999,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Mansa Konko,-15.678567,13.377312
59,60,60.0,1.0,Brikama,GMB-WST,Western,GA,The Gambia,Provincial capital,77700,6,"50,000 to 99,999",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Brikama,-16.652997,13.278996
60,61,61.0,1.0,Ziguinchor,SEN-ZGN,Ziguinchor,SG,Senegal,Provincial capital,159778,5,"100,000 to 249,999",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Ziguinchor,-16.283997,12.580002
61,62,62.0,1.0,Cacheu,GNB-CAC,Cacheu,PU,Guinea-Bissau,Provincial capital,10490,7,"Less than 50,000",45835.0,1.0,Africa,1.158346e+07,3.000115e+07,Cacheu,-16.164999,12.268998
62,63,63.0,1.0,Bolama,GNB-BOL,Bolama,PU,Guinea-Bissau,Provincial capital,10769,7,"Less than 50,000",45840.0,1.0,Africa,1.158346e+07,3.000115e+07,Bolama,-15.486003,11.583000
63,64,64.0,1.0,Bissau,GNB-BIS,Bissau,PU,Guinea-Bissau,National capital and provincial capital enclave,388028,4,"250,000 to 499,999",45838.0,1.0,Africa,1.158346e+07,3.000115e+07,Bissau,-15.597999,11.863998
64,65,65.0,1.0,Georgetown,GMB-MIS,MacCarthy Island,GA,The Gambia,Provincial capital,3584,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Georgetown,-14.767002,13.551003
65,66,66.0,1.0,Basse Santa Su,GMB-URI,Upper River,GA,The Gambia,Provincial capital,14380,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Basse Santa Su,-14.222997,13.310001
66,67,67.0,1.0,Kolda,SEN-KLD,Kolda,SG,Senegal,Provincial capital,58809,6,"50,000 to 99,999",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Kolda,-14.943996,12.899997
67,68,68.0,1.0,Farim,GNB-OIO,Oio,PU,Guinea-Bissau,Provincial capital,6792,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Farim,-15.227001,12.492999
68,69,69.0,1.0,Gabu,GNB-GAB,Gabu,PU,Guinea-Bissau,Provincial capital,14430,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Gabu,-14.234004,12.279996
69,70,70.0,1.0,Bafata,GNB-BAF,Bafata,PU,Guinea-Bissau,Provincial capital,22521,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Bafata,-14.689998,12.168000
70,71,71.0,1.0,Fulacunda,GNB-QNR,Quinara,PU,Guinea-Bissau,Provincial capital,-999,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Fulacunda,-15.194997,11.772999
71,72,72.0,1.0,Tambacounda,SEN-TMB,Tambacounda,SG,Senegal,Provincial capital,-999,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Tambacounda,-13.678002,13.772997
72,73,73.0,1.0,Koundara,GIN-KND,Koundara,GV,Guinea,Provincial capital,13990,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Koundara,-13.295997,12.480003
73,74,74.0,1.0,Mali,GIN-MLI,Mali,GV,Guinea,Provincial capital,5479,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Mali,-12.301002,12.084003
74,75,75.0,1.0,Gaoual,GIN-GAO,Gaoual,GV,Guinea,Provincial capital,7461,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Gaoual,-13.212999,11.754000
75,76,76.0,1.0,Tongue,GIN-TOU,Tougue,GV,Guinea,Provincial capital,25531,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Tongue,-11.670003,11.439999
76,77,77.0,1.0,Labe,GIN-LAB,Labe,GV,Guinea,Provincial capital,46510,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Labe,-12.299004,11.322999
77,78,78.0,1.0,Ayoun El Atrous,MRT-HEG,Hodh el Gharbi,MR,Mauritania,Provincial capital,-999,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Ayoun El Atrous,-9.617004,16.660998
78,79,79.0,1.0,Nema,MRT-HEC,Hodh ech Chargui,MR,Mauritania,Provincial capital,-999,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Nema,-7.261002,16.615998
79,80,80.0,1.0,Segou,MLI-SEG,Segou,ML,Mali,Provincial capital,92552,6,"50,000 to 99,999",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Segou,-6.255000,13.436001
80,81,81.0,1.0,Bamako,MLI-BAM,Bamako,ML,Mali,National and provincial capital,1297281,2,"1,000,000 to 4,999,999",0.0,1.0,Africa,1.158346e+07,3.000115e+07,NaN,-7.986483,12.652956
81,82,82.0,1.0,Siguiri,GIN-SIG,Siguiri,GV,Guinea,Provincial capital,43601,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Siguiri,-9.179001,11.419002
82,83,83.0,1.0,Sikasso,MLI-SKS,Sikasso,ML,Mali,Provincial capital,144786,5,"100,000 to 249,999",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Sikasso,-5.672997,11.314998
83,84,84.0,1.0,Dinguiraye,GIN-DNG,Dinguiraye,GV,Guinea,Provincial capital,6062,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Dinguiraye,-10.726002,11.298996
84,85,85.0,1.0,Timbuktu,MLI-GAO,Gao,ML,Mali,Other,32460,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Timbuktu,-3.009996,16.759998
85,86,86.0,1.0,Gao,MLI-GAO,Gao,ML,Mali,Provincial capital,57978,6,"50,000 to 99,999",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Gao,-0.051003,16.272999
86,87,87.0,1.0,Mopti,MLI-MOP,Mopti,ML,Mali,Provincial capital,108456,5,"100,000 to 249,999",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Mopti,-4.183002,14.482998
87,88,88.0,1.0,Gorom Gorom,BFA-ODL,Oudalan,UV,Burkina Faso,Provincial capital,6691,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Gorom Gorom,-0.233298,14.450004
88,89,89.0,1.0,Djibo,BFA-SOM,Soum,UV,Burkina Faso,Provincial capital,22223,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Djibo,-1.627002,14.099004
89,90,90.0,1.0,Tougan,BFA-SOR,Sourou,UV,Burkina Faso,Provincial capital,17590,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Tougan,-3.069999,13.068999
90,91,91.0,1.0,Nouna,BFA-KSS,Kossi,UV,Burkina Faso,Provincial capital,29048,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Nouna,-3.860001,12.728997
91,92,92.0,1.0,Dedougou,BFA-MHN,Mouhoun,UV,Burkina Faso,Provincial capital,45341,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Dedougou,-3.464001,12.455001
92,93,93.0,1.0,Ouahigouya,BFA-YTN,Yatenga,UV,Burkina Faso,Provincial capital,61096,6,"50,000 to 99,999",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Ouahigouya,-2.417004,13.569003
93,94,94.0,1.0,Yako,BFA-PSS,Passore,UV,Burkina Faso,Provincial capital,22904,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Yako,-2.262996,12.953997
94,95,95.0,1.0,Ziniare,BFA-OBR,Oubritenga,UV,Burkina Faso,Provincial capital,12703,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Ziniare,-1.293003,12.576996
95,96,96.0,1.0,Ouagadougou,BFA-KDG,Kadiogo,UV,Burkina Faso,National and provincial capital,1086505,2,"1,000,000 to 4,999,999",0.0,0.0,Africa,1.158346e+07,3.000115e+07,NaN,-1.670004,12.480003
96,97,97.0,1.0,Reo,BFA-SNG,Sanguie,UV,Burkina Faso,Provincial capital,37535,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Reo,-2.466945,12.333492
97,98,98.0,1.0,Koudougou,BFA-BLK,Boulkiemde,UV,Burkina Faso,Provincial capital,87347,6,"50,000 to 99,999",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Koudougou,-2.364003,12.249000
98,99,99.0,1.0,Kombissiri,BFA-BZG,Bazega,UV,Burkina Faso,Provincial capital,30137,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Kombissiri,-1.333998,12.063996
99,100,100.0,1.0,Dori,BFA-SEN,Seno,UV,Burkina Faso,Provincial capital,37806,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Dori,-0.027999,14.033997
100,101,101.0,1.0,Kaya,BFA-SNM,Sanmatenga,UV,Burkina Faso,Provincial capital,39229,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Kaya,-1.088001,13.087998
101,102,102.0,1.0,Bogande,BFA-GNG,Gnagna,UV,Burkina Faso,Provincial capital,9854,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Bogande,-0.137997,12.969000
102,103,103.0,1.0,Boulsa,BFA-NMT,Namentenga,UV,Burkina Faso,Provincial capital,17489,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Boulsa,-0.568998,12.656997
103,104,104.0,1.0,Zorgo,BFA-GNZ,Ganzourgou,UV,Burkina Faso,Provincial capital,23892,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Zorgo,-0.611001,12.242997
104,105,105.0,1.0,Koupela,BFA-KRT,Kouritenga,UV,Burkina Faso,Provincial capital,32052,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Koupela,-0.356004,12.177000
105,106,106.0,1.0,Tenkodogo,BFA-BLG,Boulgou,UV,Burkina Faso,Provincial capital,37658,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Tenkodogo,-0.359001,11.773998
106,107,107.0,1.0,Manga,BFA-ZND,Zoundweogo,UV,Burkina Faso,Provincial capital,15173,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Manga,-1.064997,11.662002
107,108,108.0,1.0,Rivercess,LBR-RVR,Rivercess,LI,Liberia,Provincial capital,-999,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Rivercess,-9.577998,5.464998
108,109,109.0,1.0,Greenville,LBR-SIN,Sino,LI,Liberia,Provincial capital,-999,7,"Less than 50,000",45952.0,0.0,Africa,1.158346e+07,3.000115e+07,Greenville,-9.036999,5.007996
109,110,110.0,1.0,Sassandra,CIV-SSS,Sassandra,IV,Cote d'Ivoire,Provincial capital,23274,7,"Less than 50,000",45965.0,1.0,Africa,1.158346e+07,3.000115e+07,Sassandra,-6.078996,4.950999
110,111,111.0,1.0,Barclayville,LBR-GKR,Grand Kru,LI,Liberia,Provincial capital,-999,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Barclayville,-8.166699,4.799997
111,112,112.0,1.0,San Pedro,CIV-SNP,San-Pedro,IV,Cote d'Ivoire,Provincial capital,-999,7,"Less than 50,000",45963.0,0.0,Africa,1.158346e+07,3.000115e+07,San Pedro,-6.636996,4.761999
112,113,113.0,1.0,Tabou,CIV-TAB,Tabou,IV,Cote d'Ivoire,Provincial capital,17134,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Tabou,-7.356996,4.416003
113,114,114.0,1.0,Harper,LBR-MRY,Maryland,LI,Liberia,Provincial capital,32661,7,"Less than 50,000",45955.0,0.0,Africa,1.158346e+07,3.000115e+07,Harper,-7.713999,4.385997
114,115,115.0,1.0,Tingrela,CIV-TNG,Tengrela,IV,Cote d'Ivoire,Provincial capital,-999,7,"Less than 50,000",0.0,0.0,Africa,1.158346e+07,3.000115e+07,Tingrela,-6.408999,10.481004
115,116,116.0,1.0,Boundiali,CIV-BNL,Boundiali,IV,Cote d'Ivoire,Provincial capital,38878,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Boundiali,-6.489000,9.522000
116,117,117.0,1.0,Odienne,CIV-ODN,Odienne,IV,Cote d'Ivoire,Provincial capital,49857,7,"Less than 50,000",0.0,1.0,Africa,1.158346e+07,3.000115e+07,Odienne,-7.577001,9.509004

In [7]:
df_jal = df_jal[['Ville', 'Mode de transport', 'Situation au 01/01/25', "KM d\'infrastructure", "Nombre d'habitants en 2024 (ville)"]]
df_jal = df_jal.rename(columns = { 'Mode de transport' : 'Mode', 'Situation au 01/01/25' : 'Situation', 'KM d\'infrastructure' : 'Km', "Nombre d'habitants en 2024 (ville)" : "hab"} ) 

dict_x = dict( zip( df_sig['CITY_NAME'], df_sig['x'] ) )
dict_y = dict( zip( df_sig['CITY_NAME'], df_sig['y'] ) )
dit_pop_rank = dict( zip( df_sig['CITY_NAME'], df_sig['POP_RANK'] ) )

In [8]:
df = df_jal.groupby( by = ['Ville', 'hab', 'Mode', 'Situation'] ).sum().reset_index()

In [9]:
df['M_S'] = df.apply(lambda x : ( x['Mode'], x['Situation'] ), axis = 1)
df['color'] = df['M_S'].map(palette)
df['x'] = df['Ville'].map(dict_x)
df['y'] = df['Ville'].map(dict_y)
df['POP_RANK'] = df['Ville'].map(dit_pop_rank)

In [11]:
df['hab'] = df['hab'].apply(lambda x : format_number(x))

In [12]:
df.head(10)

,Ville,hab,Mode,Situation,Km,M_S,color,x,y,POP_RANK
0,Abidjan,5.9M,BRT,Planned,25.0,"(BRT, Planned)",#ba96c4,-4.021893,5.324859,2
1,Abidjan,5.9M,BRT,Under construction,20.0,"(BRT, Under construction)",#a16aa9,-4.021893,5.324859,2
2,Abidjan,5.9M,Metro,Under construction,37.0,"(Metro, Under construction)",#73c4bd,-4.021893,5.324859,2
3,Abuja,4.0M,Metro,Operational,78.0,"(Metro, Operational)",#2eb4a8,7.256385,9.057267,5
4,Accra,2.7M,BHNS,Planned,24.0,"(BHNS, Planned)",#938fc1,-0.200925,5.558562,2
5,Addis Ababa,5.7M,BRT,Under construction,16.0,"(BRT, Under construction)",#a16aa9,38.700000,9.029997,2
6,Addis Ababa,5.7M,Tramway,Operational,31.0,"(Tramway, Operational)",#1984c6,38.700000,9.029997,2
7,Agadir,998k,BHNS,Planned,36.2,"(BHNS, Planned)",#938fc1,-9.611001,30.418002,3
8,Agadir,998k,BHNS,Under construction,15.5,"(BHNS, Under construction)",#6d69a9,-9.611001,30.418002,3
9,Alexandria,5.7M,Tramway,Operational,32.0,"(Tramway, Operational)",#1984c6,29.905101,31.204494,2

In [ ]:
for ville in df["Ville"].unique():
    
    print(ville)
    
    df_ville = df[df["Ville"] == ville]
    grouped = df_ville.groupby(["Mode", "Situation"])
    sorted_groups = sorted(grouped.groups.keys(), key=lambda x: (situation_order.index(x[1]), transport_order.index(x[0])))
    
    bottoms = {}
    
    fig, ax = plt.subplots(figsize=(6, 0.8 * len(df_ville["Mode"].unique())))

    
    for (mode, situation) in sorted_groups:
        group = grouped.get_group((mode, situation))
        base = bottoms.get(mode, 0)
        
        for i, row in group.iterrows():
            ax.barh(
                mode,
                row["Km"], 
                color=row["color"], 
                left=base,
                label=row["Situation"] if row["Situation"] not in ax.get_legend_handles_labels()[1] else ""
            )
            
            ax.text(base + row["Km"] / 2, mode, 
                    int(row["Km"]), 
                    va='center', ha='center', fontproperties=poppins_semibold, fontsize=14, color='white')
            
            base += row["Km"]
        
        bottoms[mode] = base 
    
    yticks = ax.get_yticks()
    for tick, mode in zip(yticks, df_ville["Mode"].unique()):
        if mode in mode_icons:
            icon_path = mode_icons[mode]
            img = mpimg.imread(icon_path)
            imagebox = OffsetImage(img, zoom=0.8)
            ab = AnnotationBbox(imagebox, (0, tick), frameon=False, xybox=(-30, 0), xycoords='data', boxcoords='offset points')
            ax.add_artist(ab)
    
    ax.set_yticklabels([]) 
    xticks = ax.get_xticks()
    xticklabels = [str(int(tick)) if tick != max(xticks) else f"{int(tick)} km" for tick in xticks]
    ax.set_xticks(xticks)
    ax.set_xticklabels(xticklabels)

    # fr
    str_population_fr = row['Ville'] + " (" + row['hab'] + " hab.)"    
    ax.set_title(str_population_fr, fontproperties=poppins_semibold, pad = 15, fontsize = 12)   
    plt.savefig(os.path.join('./img/fr/', ville + ".png"), dpi=200, bbox_inches="tight")

    # en
    str_population_en = str_population = row['Ville'] + " (" + row['hab'] + " inhab.)"
    ax.set_title(str_population_en, fontproperties=poppins_semibold, pad = 15, fontsize = 12)   
    plt.savefig(os.path.join('./img/en/', ville + ".png"), dpi=200, bbox_inches="tight")
        
    plt.show()

In [18]:
features = []

for idx, row in df_sig.iterrows():
        
        ville = row['Name']
        # couleur : état le plus avancé, tout transports confondus
        df_ville = df[df['Ville'] == ville]
        if len(df_ville) > 0:
            df_ville["Situation"] = pd.Categorical(df_ville["Situation"], categories=situation_order, ordered=True)
            df_sorted = df_ville.sort_values("Situation")
        
            color = df_sorted.iloc[-1]['color']
            pop_rank = df_sorted.iloc[-1]['POP_RANK']
            
            if ville in df['Ville'].unique():
                feature = geojson.Feature(
                        geometry=geojson.Point((float(row["x"]), float(row["y"]))),
                        properties={
                            "name": ville,
                            "img_path": ville + ".png",
                            "color" : color,
                            "POP_RANK" : int(pop_rank)
                        },
                    )
            
                features.append(feature)


feature_collection = geojson.FeatureCollection(features)

with open("villes_africaines.geojson", "w") as f:
    geojson.dump(feature_collection, f)

C:\Users\ade\AppData\Local\Temp\ipykernel_7352\1565848347.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ville["Situation"] = pd.Categorical(df_ville["Situation"], categories=situation_order, ordered=True)